env:
  browser: true
  es2020: true
  jest: true
  node: true

extends:
  - eslint:recommended
  - airbnb
  - airbnb/hooks
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
  - plugin:jsx-a11y/recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
  - prettier/react

globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  alert: readonly
  console: readonly
  document: readonly
  $: readonly

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2020
  sourceType: module
  project: ./tsconfig.json

plugins:
  - import
  - jsx-a11y
  - react
  - react-hooks
  - '@typescript-eslint'

settings:
  import/resolver: webpack

rules:
  # Remove rules from default eslint configuration.
  # e.g. indent, semi, quotes.
  linebreak-style:
    - error
    - unix
  
  # Overwrite default and airbnb rules
  no-undef: error
  no-unused-expressions: off
  no-param-reassign: off
  camelcase:
    - error
    - allow:
      - user_id
      - showcase_id
      - crystal_id

  jsx-a11y/no-autofocus: off
  jsx-a11y/no-onchange: off
  jsx-a11y/media-has-caption: off

  # Add import rules
  import/no-unresolved: off
  import/prefer-default-export: off

  # Add react rules
  react/forbid-prop-types: off
  react/jsx-boolean-value: off
  react/require-default-props: off

  # Add react-hooks rules
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: off
