env:
  browser: true
  es2020: true
  jest: true
  node: true

extends:
  - eslint:recommended
  - airbnb
  - airbnb/hooks
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
  - plugin:jest/recommended
  - plugin:jsx-a11y/recommended
  - plugin:prettier/recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - prettier/react
  - prettier/@typescript-eslint

globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  alert: readonly
  console: readonly
  document: readonly
  $: readonly

parser: "@typescript-eslint/parser"

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2020
  sourceType: module
  project: ./tsconfig.json

plugins:
  - import
  - jsx-a11y
  - react
  - prettier
  - react-hooks
  - "@typescript-eslint"

settings:
  import/resolver: webpac

rules:
  camelcase:
    - error
    - allow:
      - user_id
  import/extensions:
    - error
    - tsx: ignorePackages
      ts: ignorePackages 
      js: ignorePackages
  import/no-unresolved: off
  import/prefer-default-export: off
  jsx-a11y/no-autofocus: off
  jsx-a11y/no-onchange: off
  jsx-a11y/media-has-caption: off
  linebreak-style:
    - error
    - unix
  react/forbid-prop-types: off
  react/jsx-boolean-value: off
  react/jsx-filename-extension: 
    - error
    - extensions:
      - .tsx
      - .ts
      - .js
  react/require-default-props: off
  react-hooks/exhaustive-deps: off
  react-hooks/rules-of-hooks: error
  no-param-reassign: off

