version: "3.7"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: rrstp-img:latest
    ports:
      -  8080:8080
    volumes:
      - .:/container
    container_name: rrstp-ctr
    tty: true
