version: "3.7"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: rrtp-img:latest
    ports:
      - 8000:8000 # webpack-dev-server
      - 8001:8001 # storybook
    volumes:
      - .:/proj-cont
    container_name: rrtp-cont
    tty: true
