// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`Storyshots TaskList Default 1`] = `
<div
  style={
    Object {
      "padding": "3rem",
    }
  }
>
  <div
    className="list-items"
  >
    <div
      className="list-item TASK_INBOX"
    >
      <label
        className="checkbox"
        htmlFor="cbInput"
      >
        <input
          defaultChecked={false}
          disabled={true}
          id="cbInput"
          name="checked"
          type="checkbox"
        />
        <span
          className="checkbox-custom"
          onClick={[Function]}
          onKeyDown={[Function]}
          role="button"
          tabIndex={0}
        />
      </label>
      <div
        className="title"
      >
        <input
          placeholder="Input title"
          readOnly={true}
          type="text"
          value="Task 1"
        />
      </div>
      <div
        className="actions"
        onClick={[Function]}
        onKeyDown={[Function]}
        role="button"
        tabIndex={0}
      />
    </div>
    <div
      className="list-item TASK_INBOX"
    >
      <label
        className="checkbox"
        htmlFor="cbInput"
      >
        <input
          defaultChecked={false}
          disabled={true}
          id="cbInput"
          name="checked"
          type="checkbox"
        />
        <span
          className="checkbox-custom"
          onClick={[Function]}
          onKeyDown={[Function]}
          role="button"
          tabIndex={0}
        />
      </label>
      <div
        className="title"
      >
        <input
          placeholder="Input title"
          readOnly={true}
          type="text"
          value="Task 2"
        />
      </div>
      <div
        className="actions"
        onClick={[Function]}
        onKeyDown={[Function]}
        role="button"
        tabIndex={0}
      />
    </div>
    <div
      className="list-item TASK_INBOX"
    >
      <label
        className="checkbox"
        htmlFor="cbInput"
      >
        <input
          defaultChecked={false}
          disabled={true}
          id="cbInput"
          name="checked"
          type="checkbox"
        />
        <span
          className="checkbox-custom"
          onClick={[Function]}
          onKeyDown={[Function]}
          role="button"
          tabIndex={0}
        />
      </label>
      <div
        className="title"
      >
        <input
          placeholder="Input title"
          readOnly={true}
          type="text"
          value="Task 3"
        />
      </div>
      <div
        className="actions"
        onClick={[Function]}
        onKeyDown={[Function]}
        role="button"
        tabIndex={0}
      />
    </div>
    <div
      className="list-item TASK_INBOX"
    >
      <label
        className="checkbox"
        htmlFor="cbInput"
      >
        <input
          defaultChecked={false}
          disabled={true}
          id="cbInput"
          name="checked"
          type="checkbox"
        />
        <span
          className="checkbox-custom"
          onClick={[Function]}
          onKeyDown={[Function]}
          role="button"
          tabIndex={0}
        />
      </label>
      <div
        className="title"
      >
        <input
          placeholder="Input title"
          readOnly={true}
          type="text"
          value="Task 4"
        />
      </div>
      <div
        className="actions"
        onClick={[Function]}
        onKeyDown={[Function]}
        role="button"
        tabIndex={0}
      />
    </div>
    <div
      className="list-item TASK_INBOX"
    >
      <label
        className="checkbox"
        htmlFor="cbInput"
      >
        <input
          defaultChecked={false}
          disabled={true}
          id="cbInput"
          name="checked"
          type="checkbox"
        />
        <span
          className="checkbox-custom"
          onClick={[Function]}
          onKeyDown={[Function]}
          role="button"
          tabIndex={0}
        />
      </label>
      <div
        className="title"
      >
        <input
          placeholder="Input title"
          readOnly={true}
          type="text"
          value="Task 5"
        />
      </div>
      <div
        className="actions"
        onClick={[Function]}
        onKeyDown={[Function]}
        role="button"
        tabIndex={0}
      />
    </div>
    <div
      className="list-item TASK_INBOX"
    >
      <label
        className="checkbox"
        htmlFor="cbInput"
      >
        <input
          defaultChecked={false}
          disabled={true}
          id="cbInput"
          name="checked"
          type="checkbox"
        />
        <span
          className="checkbox-custom"
          onClick={[Function]}
          onKeyDown={[Function]}
          role="button"
          tabIndex={0}
        />
      </label>
      <div
        className="title"
      >
        <input
          placeholder="Input title"
          readOnly={true}
          type="text"
          value="Task 6"
        />
      </div>
      <div
        className="actions"
        onClick={[Function]}
        onKeyDown={[Function]}
        role="button"
        tabIndex={0}
      />
    </div>
  </div>
</div>
`;

exports[`Storyshots TaskList Empty 1`] = `
<div
  style={
    Object {
      "padding": "3rem",
    }
  }
>
  <div
    className="list-items"
  >
    empty
  </div>
</div>
`;

exports[`Storyshots TaskList Loading 1`] = `
<div
  style={
    Object {
      "padding": "3rem",
    }
  }
>
  <div
    className="list-items"
  >
    loading
  </div>
</div>
`;

exports[`Storyshots TaskList With Pinned Tasks 1`] = `
<div
  style={
    Object {
      "padding": "3rem",
    }
  }
>
  <div
    className="list-items"
  >
    <div
      className="list-item TASK_INBOX"
    >
      <label
        className="checkbox"
        htmlFor="cbInput"
      >
        <input
          defaultChecked={false}
          disabled={true}
          id="cbInput"
          name="checked"
          type="checkbox"
        />
        <span
          className="checkbox-custom"
          onClick={[Function]}
          onKeyDown={[Function]}
          role="button"
          tabIndex={0}
        />
      </label>
      <div
        className="title"
      >
        <input
          placeholder="Input title"
          readOnly={true}
          type="text"
          value="Task 1"
        />
      </div>
      <div
        className="actions"
        onClick={[Function]}
        onKeyDown={[Function]}
        role="button"
        tabIndex={0}
      />
    </div>
    <div
      className="list-item TASK_INBOX"
    >
      <label
        className="checkbox"
        htmlFor="cbInput"
      >
        <input
          defaultChecked={false}
          disabled={true}
          id="cbInput"
          name="checked"
          type="checkbox"
        />
        <span
          className="checkbox-custom"
          onClick={[Function]}
          onKeyDown={[Function]}
          role="button"
          tabIndex={0}
        />
      </label>
      <div
        className="title"
      >
        <input
          placeholder="Input title"
          readOnly={true}
          type="text"
          value="Task 2"
        />
      </div>
      <div
        className="actions"
        onClick={[Function]}
        onKeyDown={[Function]}
        role="button"
        tabIndex={0}
      />
    </div>
    <div
      className="list-item TASK_INBOX"
    >
      <label
        className="checkbox"
        htmlFor="cbInput"
      >
        <input
          defaultChecked={false}
          disabled={true}
          id="cbInput"
          name="checked"
          type="checkbox"
        />
        <span
          className="checkbox-custom"
          onClick={[Function]}
          onKeyDown={[Function]}
          role="button"
          tabIndex={0}
        />
      </label>
      <div
        className="title"
      >
        <input
          placeholder="Input title"
          readOnly={true}
          type="text"
          value="Task 3"
        />
      </div>
      <div
        className="actions"
        onClick={[Function]}
        onKeyDown={[Function]}
        role="button"
        tabIndex={0}
      />
    </div>
    <div
      className="list-item TASK_INBOX"
    >
      <label
        className="checkbox"
        htmlFor="cbInput"
      >
        <input
          defaultChecked={false}
          disabled={true}
          id="cbInput"
          name="checked"
          type="checkbox"
        />
        <span
          className="checkbox-custom"
          onClick={[Function]}
          onKeyDown={[Function]}
          role="button"
          tabIndex={0}
        />
      </label>
      <div
        className="title"
      >
        <input
          placeholder="Input title"
          readOnly={true}
          type="text"
          value="Task 4"
        />
      </div>
      <div
        className="actions"
        onClick={[Function]}
        onKeyDown={[Function]}
        role="button"
        tabIndex={0}
      />
    </div>
    <div
      className="list-item TASK_INBOX"
    >
      <label
        className="checkbox"
        htmlFor="cbInput"
      >
        <input
          defaultChecked={false}
          disabled={true}
          id="cbInput"
          name="checked"
          type="checkbox"
        />
        <span
          className="checkbox-custom"
          onClick={[Function]}
          onKeyDown={[Function]}
          role="button"
          tabIndex={0}
        />
      </label>
      <div
        className="title"
      >
        <input
          placeholder="Input title"
          readOnly={true}
          type="text"
          value="Task 5"
        />
      </div>
      <div
        className="actions"
        onClick={[Function]}
        onKeyDown={[Function]}
        role="button"
        tabIndex={0}
      />
    </div>
    <div
      className="list-item TASK_PINNED"
    >
      <label
        className="checkbox"
        htmlFor="cbInput"
      >
        <input
          defaultChecked={false}
          disabled={true}
          id="cbInput"
          name="checked"
          type="checkbox"
        />
        <span
          className="checkbox-custom"
          onClick={[Function]}
          onKeyDown={[Function]}
          role="button"
          tabIndex={0}
        />
      </label>
      <div
        className="title"
      >
        <input
          placeholder="Input title"
          readOnly={true}
          type="text"
          value="Task 6 (pinned)"
        />
      </div>
      <div
        className="actions"
        onClick={[Function]}
        onKeyDown={[Function]}
        role="button"
        tabIndex={0}
      />
    </div>
  </div>
</div>
`;
